---
title: "Icons"
author: "Sameer Rau"
date: "4/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set
library(tidyverse)
library(hexSticker)
library(showtext)
```

# Fonts
```{r}
font_add_google("Source Sans Pro", family = "Source Sans Pro")
```


# Name
```{r}
# sticker("./files/nameimage.JPG", package="Sameer Rau", p_size=5, p_color="white", p_family = "Source Sans Pro", p_x=1, p_y=0.5, h_color = "#5c8a6f", h_fill = "white", asp = 0.9, s_x = 0.4, s_y = 1, s_width = 2.2, filename="files/profilepicture.png")
```

# P1
```{r}
sticker("./files/image1.png", package="1", p_size=5, p_color="black", p_family = "Source Sans Pro", s_x=1, s_y=.75, s_width=0.6,  h_color = "black", h_fill = "yellow", asp = 0.9, filename="files/image1.png")
```

# P2
```{r}
sticker("./files/image2.png", package="2", p_size=5, p_color="red", p_family = "Source Sans Pro", s_x=1, s_y=0.75, s_width=0.6, h_color = "red", h_fill = "white", asp = 0.9, filename="files/image2.png")
```

# I1
```{r}
sticker("./files/a1.png", package="A1", p_size=5, p_color="blue", p_family = "Source Sans Pro", s_x=1, s_y=0.7, s_width=0.4, h_color = "blue", h_fill = "#F6F7E4", asp = 0.9, filename="files/a1.png")
```

# I2
```{r}
sticker("./files/a2.png", package="A2", p_size=5, p_color="white", p_family = "Source Sans Pro",  s_x=1, s_y=0.75, s_width=0.4, h_color = "white", h_fill = "#5B1404", asp = 0.9, filename="files/a2.png")
